# CS 620, Fall 2012
# Assignment 4
# 
# Makefile for simulating a shell that accepts only external commands.
#
# Carmen St. Jean (crr8)
# October 3, 2012
#
myshell: myshell.c myshell.h
	gcc -Wall myshell.c -o myshell 
