# CS 620, Fall 2012
# Assignment 11 - PART TWO
# 
# Makefile for simulating a simple memory manager based
# on the contiguous memory allocation scheme.
#
# Carmen St. Jean (crr8)
# December 3, 2012
#
ffcompact: ffcompact.c
	gcc -Wall ffcompact.c -o ffcompact 
