# CS 620, Fall 2012
# Assignment 4
# 
# Makefile for simulating a shell that accepts only external commands.
#
# Carmen St. Jean (crr8)
# October 3, 2012
#
barber: barber.c
	gcc -lrt -lpthread -lm barber.c -o barber 
