# CS 620, Fall 2012
# Assignment 11 - PART ONE
# 
# Makefile for simulating a simple memory manager based
# on the contiguous memory allocation scheme.
#
# Carmen St. Jean (crr8)
# December 3, 2012
#
firstfit: firstfit.c
	gcc -Wall firstfit.c -o firstfit 
